services:
  backend:
    build: ./backend-fastapi
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend-fastapi/.env
    volumes:
      - ./backend-fastapi:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
